name: city
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  carousel_slider: ^4.2.1
  email_validator: ^2.1.17
  firebase_core: ^2.28.0
  flutter:
    sdk: flutter
  flutter_config: ^2.0.2
  flutter_speed_dial: ^7.0.0
  google_maps_flutter: ^2.6.0
  intl: ^0.19.0
  provider: ^6.1.2
  timeago_flutter: ^3.6.0
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
